import { IconMetadata } from "../../types";

const tpaIconsMetadata: Array<IconMetadata> = [
   {
    title: "Calendar",
    category: "General",
    description: "",
    tags: [],
    sizes: { "32":"CalendarLarge" },
  },
  {
    title: "Clock",
    category: "General",
    description: "",
    tags: [],
    sizes: { "32":"ClockLarge" },
  },
  {
    title: "Comment",
    category: "General",
    description: "",
    tags: [],
    sizes: { "32":"CommentLarge" },
  },
  {
    title: "Document",
    category: "General",
    description: "",
    tags: [],
    sizes: { "32":"DocumentLarge" },
  },
  {
    title: "Email",
    category: "General",
    description: "",
    tags: [],
    sizes: { "32":"EmailLarge" },
  },
  {
    title: "Indeterminate",
    category: "General",
    description: "",
    tags: [],
    sizes: { "16": "IndeterminateXSmall" }
  },
  {
    title: "Percent",
    category: "General",
    description: "",
    tags: [],
    sizes: { "32":"PercentLarge" },
  },
  {
    title: "Reaction",
    category: "General",
    description: "",
    tags: [],
    sizes: { "32":"ReactionLarge" },
  },
  {
    title: "Tag",
    category: "General",
    description: "",
    tags: [],
    sizes: { "32":"TagLarge" },
  },
  {
    title: "Check",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"16":"CheckXSmall" },
  },
  {
    title: "Clear",
    category: "Actions",
    description: "",
    tags: [],
    sizes: { "16":"ClearXSmall" },
  },
  {
    title: "Close",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"12":"CloseXXSmall", "16":"CloseXSmall", "32":"CloseLarge" },
  },
  {
    title: "Delete",
    category: "Actions",
    description: "",
    tags: [],
    sizes: { "32":"DeleteLarge" },
  },
  {
    title: "Edit",
    category: "Actions",
    description: "",
    tags: [],
    sizes: { "32":"EditLarge" },
  },
  {
    title: "ExternalLink",
    category: "Actions",
    description: "",
    tags: [],
    sizes: { "32":"ExternalLinkLarge" },
  },
  {
    title: "Link",
    category: "Actions",
    description: "",
    tags: [],
    sizes: { "32":"LinkLarge" },
  },
  {
    title: "Minus",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"16":"MinusXSmall", "32":"MinusLarge" },
  },
  {
    title: "Plus",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"16":"PlusXSmall", "32":"PlusLarge" },
  },
  {
    title: "Favorite",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "32":"FavoriteLarge" },
  },
  {
    title: "FavoriteFill",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "32":"FavoriteFillLarge" },
  },
  {
    title: "LikeHeart",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "32":"LikeHeartLarge", },
  },
  {
    title: "LikeHeartFill",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "32":"LikeHeartFillLarge" },
  },
  {
    title: "LockFill",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: {"16":"LockFillXSmall" },
  },
  {
    title: "Select",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "32":"SelectLarge" },
  },
  {
    title: "SelectFill",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "32":"SelectFillLarge" },
  },
  {
    title: "Visible",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "32":"VisibleLarge" },
  },
  {
    title: "Camera",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "32":"CameraLarge" },
  },
  {
    title: "Image",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "32":"ImageLarge" },
  },
  {
    title: "PlayButton",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "32":"PlayButtonLarge" },
  },
  {
    title: "PlayFill",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "32":"PlayFillLarge" },
  },
  {
    title: "Video",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "32":"VideoLarge" },
  },
  {
    title: "VideoFill",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "16":"VideoFillXSmall" },
  },
  {
    title: "Error",
    category: "Notifications",
    description: "",
    tags: [],
    sizes: { "32":"ErrorLarge" },
  },
  {
    title: "Notifications",
    category: "Notifications",
    description: "",
    tags: [],
    sizes: { "32":"NotificationsLarge" },
  },
  {
    title: "NotificationsFill",
    category: "Notifications",
    description: "",
    tags: [],
    sizes: { "32":"NotificationsFillLarge" },
  },
  {
    title: "ChevronDown",
    category: "Chevrons",
    description: "",
    tags: [],
    sizes: { "16":"ChevronDownXSmall", "32":"ChevronDownLarge", "60":"ChevronDownXLarge" },
  },
  {
    title: "ChevronLeft",
    category: "Chevrons",
    description: "",
    tags: [],
    sizes: { "16":"ChevronLeftXSmall", "32":"ChevronLeftLarge", "60":"ChevronLeftXLarge" },
  },
  {
    title: "ChevronRight",
    category: "Chevrons",
    description: "",
    tags: [],
    sizes: { "16":"ChevronRightXSmall", "32":"ChevronRightLarge", "60":"ChevronRightXLarge" },
  },
  {
    title: "ChevronUp",
    category: "Chevrons",
    description: "",
    tags: [],
    sizes: { "16":"ChevronUpXSmall", "32":"ChevronUpLarge", "60":"ChevronUpXLarge" },
  },
  {
    title: "DoubleChevronRight",
    category: "Chevrons",
    description: "",
    tags: [],
    sizes: { "32":"DoubleChevronRightLarge" },
  },
  {
    title: "DoubleChevronLeft",
    category: "Chevrons",
    description: "",
    tags: [],
    sizes: { "32":"DoubleChevronLeftLarge" },
  },
  {
    title: "Blog",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "32":"BlogLarge" },
  },
  {
    title: "Bookings",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "32":"BookingsLarge" },
  },
  {
    title: "Events",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "32":"EventsLarge" },
  },
  {
    title: "Forums",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "32":"ForumsLarge" },
  },
  {
    title: "Hotels",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "32":"HotelsLarge" },
  },
  {
    title: "Stores",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "32":"StoresLarge" },
  },
  {
    title: "SpoilerAlert",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "40":"SpoilerAlertLarge" },
  },
];

export default tpaIconsMetadata;
